### ISSUE TITLE
SS-2 bug

### ISSUE THREAD

**Issue by AlHeeley** [VCVRack/Fundamental#82]
SS-2 in rack 1.01 on mac no ports seem to work, tried deleting Fundamental folder & reinstalling from rack, but no success.

**Comment by AndrewBelt** [comment]
I can't reproduce, and this was fixed a while ago. Can you specify which Fundamental version you're using?

**Comment by AlHeeley** [comment]
Latest one reinstalled last night - 1.01 I think.

**Comment by AlHeeley** [comment]
Ports 2 and 4 not receptive to tone change with seq input, unit doesn't seem to function for key changes when used in conjunction with ML Constants.

**Comment by Petervos2018** [comment]
@AndrewBelt 
Here is a simple vcv file to show what's going wrong.
As soon as the first port has no input it does not matter what you put into 2-4 they will stay at 0.0V.
As seen in this pic : 

![SS2Bug-24072019-111](https://user-images.githubusercontent.com/46076474/61825324-69679400-ae60-11e9-8f85-c7d8ea66891f.jpg)

And here is the (zipped) file for you to test : 
[SS2-BUG-111-24072019.zip](https://github.com/VCVRack/Fundamental/files/3428614/SS2-BUG-111-24072019.zip)

**Comment by Amy-Triptyline** [comment]
Maybe I'm missing a thread somewhere, but in Rack 1.1.5 this still doesn't work.

If an input is NOT present at the first port, the other three ports (2-4) output nothing regardless of either the number of active inputs on the three ports in question (2-4) or of the actual switch configuration (i.e 2, 3 or 4)

Fundamental 1.2.1 
Rack 1.1.5
Macbook Pro 10.13.6

**Comment by AndrewBelt** [comment]
Duplicate of https://github.com/VCVRack/Fundamental/issues/92, which was solved.
